### PR TITLE
Correcting teradata connector export parameter names as per documenation

### PR DESCRIPTION
**Pull request by jithinjohn**
Teradata connector boolean parameters were typed incorrectly. Correcting the same as per documenation  http://www.cloudera.com/documentation/other/connectors/teradata/1-x/topics/cctd_use_tpcc.html

### CODE REVIEW

**Comment by rowandavies** [comment]
👍

**Comment by toddmowen** [comment]
@jithinjohn Once this is merged, will you be updating maestro and etl.util to pull in the new jar? Fortunately that's only 2 downstream repos to change, so feasible to do manually. Still, if you'd like to try the (semi) automatic approach to bumping versions with [autowrangler](https://github.com/CommBank/autowrangler), I can help you get started.

Incidentally, is there are reason for leaving the spelling of the `--teradata-force-staging` and `--teradata-skip-xview` parameters unchanged? The asymmetry introduced by this PR is a bit...unsatisfying.

**Comment by toddmowen** [comment]
@jithinjohn Thinking further about the question of how to make this change available in the ETL job. I'm worried I may have left you in an awkward situation, because I'm only halfway through the process of updating the stack to use scalding 0.16.0. What you should know is:

* This repo has already been updated to depend on scalding 0.16.0 (via uniform 1.12).
* Scalding 0.16.0 has not yet been tested on the cluster, so there is some small risk attached.
* The update has only progressed as far as util.etl; none of the libraries on Stash have been updated.

Is the ETL job using houston? I've only just had a look at that side today, and I'm not even sure what is required to bump this change up to util.houston *properly*.

The maestro folk may be able to suggest a better solution, but given the apparent urgency of the change, what *I* would do at this point is to *revert commits 3f30007 and 88aaac9* as part of this PR. Then, once the PR is merged and the artifact is published, use `dependencyOverrides` in the ETL job to pull in the new version of parlour. (That would mean taking on some technical debt, as the `dependencyOverrides` would need to be removed next time the util.houston version is bumped).

OTOH if you are not using houston, then it's a different story.

**Comment by jithinjohn** [comment]
@toddmowen I have changed  `--teradata-force-staging` and  `--teradata-skip-xview`. I can update maestro and util.etl as well.

Regarding the change, it will bring a change to datahub export template in `util.etl` . No teradata ETL jobs are using houston at this point. I have also tested one sample export job in cluster with this change.

**Comment by toddmowen** [comment]
:+1: (given that it has already been tested on cluster)

**Pull request merged**
